-- Create Products Table (if not exists)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  barcode text unique not null,
  name text not null,
  price numeric not null check (price >= 0),
  variant text -- New column for Size/Unit
);

-- Add column if table exists but column missing
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'products' and column_name = 'variant') then
    alter table public.products add column variant text;
  end if;
end $$;

-- Create Bills Table
create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  total_amount numeric not null,
  vat_amount numeric not null,
  payment_method text check (payment_method in ('cash', 'card', 'other')) default 'cash'
);

-- Create Bill Items Table (Line Items)
create table if not exists public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint references public.bills(id) on delete cascade not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  price_at_sale numeric not null,
  total numeric not null
);

-- Security Policies (RLS)
-- 1. Enable RLS
alter table public.products enable row level security;
alter table public.bills enable row level security;
alter table public.bill_items enable row level security;

-- 2. Drop old policies if they exist to avoid conflicts
drop policy if exists "Enable all access" on public.products;
drop policy if exists "Enable all access" on public.bills;
drop policy if exists "Enable all access" on public.bill_items;

-- 3. Create permissive policies for Insert/Select/Etc.
create policy "Enable all access" on public.products for all using (true) with check (true);
create policy "Enable all access" on public.bills for all using (true) with check (true);
create policy "Enable all access" on public.bill_items for all using (true) with check (true);
